# TCL File Generated by Component Editor 18.1
# Sat Nov 23 18:54:24 PST 2024
# DO NOT MODIFY


# 
# vga_avalon "vga_avalon" v1.0
#  2024.11.23.18:54:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_avalon.sv SYSTEM_VERILOG PATH ../task4/vga_avalon.sv TOP_LEVEL_FILE
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH ../vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH ../vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH ../vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH ../vga-core/vga_pll.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_avalon.sv SYSTEM_VERILOG PATH ../task4/vga_avalon.sv
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH ../vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH ../vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH ../vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH ../vga-core/vga_pll.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end vga_red vga_red Output 8
add_interface_port conduit_end vga_grn vga_grn Output 8
add_interface_port conduit_end vga_blu vga_blu Output 8
add_interface_port conduit_end vga_hsync vga_hsync Output 1
add_interface_port conduit_end vga_vsync vga_vsync Output 1
add_interface_port conduit_end vga_clk vga_clk Output 1

